user_token: NmE0YzRjMzEtNTM2Zi00NDY5LThmNzItZTE1YmE2MTZkNGE4XzgwNg==

session:
  key: ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: postgres
  database: postgres
bot:
  token: 8d37c34433c44321a0213cc1bb6a4091590c516c044131c98257ea1585d0a706460833891fcb556d31b0c
  group_id: 210547650


