"""first migration

Revision ID: 22f64dab6143
Revises: fe94f041b970
Create Date: 2021-09-05 00:31:08.547574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f64dab6143'
down_revision = 'fe94f041b970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
