"""first migration

Revision ID: f44bc5b31089
Revises: 95aedccde21e
Create Date: 2021-09-04 23:31:44.180372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44bc5b31089'
down_revision = '95aedccde21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_is_correct_key', 'answers', type_='unique')
    op.drop_constraint('answers_title_key', 'answers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('answers_title_key', 'answers', ['title'])
    op.create_unique_constraint('answers_is_correct_key', 'answers', ['is_correct'])
    # ### end Alembic commands ###
